(base) root@autodl-container-91d74fb88e-2bbb3f11:~/autodl-tmp/caiqiyue/code_from_paper# curl -I github.com
HTTP/1.1 301 Moved Permanently
Connection: keep-alive
Keep-Alive: timeout=4
Location: https://github.com/
Proxy-Connection: keep-alive
Content-Length: 0

(base) root@autodl-container-91d74fb88e-2bbb3f11:~/autodl-tmp/caiqiyue/code_from_paper# 